title: title 
author: author 
  name: name
  email: change@email.com
  #street_address:
  city: city
  state: state 
  zip_code: zip_code 
  country: country 
  #phone: phone
description: > # this means to ignore newlines until "show_excerpts:"
   Change description
show_excerpts: false
# Set to `true` to show excerpts on the homepage.
#

# Build settings

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  date_format: "%b %-d, %Y"
  # date_format: "%Y-%m-%d %I:%M:%S.%L %p %Z" # "%b %-d, %Y"
  # Generate social links
  #
  # Don't have accounts in those items commented out, but what the heck!?
  social_links:
     - { platform: devto,          user_url: "https://dev.to/username"}
  #   - { platform: dribbble,       user_url: "https://dribbble.com/username" }
  #   - { platform: facebook,       user_url: "https://www.facebook.com/username" }
     - { platform: flickr,         user_url: "https://www.flickr.com/photos/username" }
     - { platform: github,         user_url: "https://github.com/jekyll/username" }
  #   - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #   - { platform: instagram,      user_url: "https://www.instagram.com/username" }
  #   - { platform: keybase,        user_url: "https://keybase.io/username" }
     - { platform: linkedin,       user_url: "https://www.linkedin.com/in/username" }
  #   - { platform: microdotblog,   user_url: "https://micro.blog/username" }
  #   - { platform: pinterest,      user_url: "https://www.pinterest.com/username" }
     - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/[1-9][0-9]*/username" }
  #   - { platform: telegram,       user_url: "https://t.me/username" }
  #   - { platform: twitter,        user_url: "https://twitter.com/username" }
     - { platform: youtube,        user_url: "https://www.youtube.com/@username" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
# header_pages:
#   - about.md
